### ISSUE TITLE
Issue compiling pbmpi 

### ISSUE THREAD

**Issue by zhoulhca** [bayesiancook/pbmpi#10]
Hi there, 

I am trying to install pbmpi onto a linux ubuntu server. When executing the make command, this is what I get: 
mpic++ -c -w -O3 -c PB.cpp
PB.cpp: In function ‘int main(int, char**)’:
PB.cpp:32:34: error: ‘MPI_Type_extent’ was not declared in this scope
  MPI_Type_extent(MPI_DOUBLE,&dtex);
                                  ^
PB.cpp:34:66: error: ‘MPI_Type_struct’ was not declared in this scope
  MPI_Type_struct(2,blockcounts,displacements,types,&Propagate_arg);
                                                                  ^
make: *** [PB.o] Error 1

Is there something wrong with the server I'm trying to install it in? I'm not quite sure how exactly to fix this issue. Thanks for all the work that you do!

**Comment by trecakov** [comment]
I just faced the same issue. I do not think its the issue with the server that you are installing. There is an error at PB.cpp file. We should wait for developers to double check this.

**Comment by bayesiancook** [comment]
Hi,
thanks for the feedback. the problem should be fixed now -- can you have a try and tell me if this works now?
best, nicolas L

**Comment by trecakov** [comment]
@bayesiancook This fixes the issue. Thank you!
@zhoulhca You may want to try it now.

**Comment by zhoulhca** [comment]
@bayesiancook No more issues, thank you!
