### ISSUE TITLE
please provide release tag

### ISSUE THREAD

**Issue by EricDeveaud** [bayesiancook/pbmpi#13]
Hello, 

I would request that you provide release tag please.
or at least versioned frozen archive on home page

regards

Eric

**Comment by tardigradus** [comment]
+1

I would also very much welcome this.

For software management systems, such as [EasyBuild](https://easybuild.readthedocs.io), which are used by HPC sites, installation of packages can only be automated if programs have well-defined versions.  If such automation is in place, it means that users can be provided with software much more quickly (some overstretched administrators could even be unwilling to install software which is hard to integrate into their provisioning mechanism).

More generally it is of great importance to science that research is reproducible and for this it must be clear which version of which software was used to obtain a particular research result.

**Comment by tardigradus** [comment]
Just to be clear, I would favour the use of tags to mark software releases.

**Comment by bayesiancook** [comment]
sorry for the slow reply

I have tagged the current version (has been stable for ~ 1 year)

**Comment by EricDeveaud** [comment]
sorry, 
forgot to say thanks
