### ISSUE TITLE
error during cross validation

### ISSUE THREAD

**Issue by mgiacom** [bayesiancook/pbmpi#15]
Hello!

I am running a cross validation for 3 models (CAT-GTR, CAT-F81 and LG-C60), but I am having an issue in the last step (readpb_mpi -cv cvb1_test.ali -x 100 10 CAT_GTRcvb1_learn.ali) ONLY on the CAT-GTR analysis:

read data from file : cvb1_learn.ali
number of taxa  : 38
number of sites : 262978
number of states: 20
read data from file : cvb1_test.ali
number of taxa  : 38
number of sites : 29219
number of states: 20
burnin: 100
every 10 points until 1100
.-432731
.-432768
.-432748
.-432743
.-432773
.-432737
.-432737
.-432705
.-432731
.-432700
.-432752
.-432705
.-432702
.-432736
.error in DrawUniformizedSubstitutionNumber: normalising constant
1.46526e-08	1.44747e-08
2.51613
5
18	19
terminate called without an active exception

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   PID 108725 RUNNING AT bp1-13-13-04.data.bp.acrc.priv
=   EXIT CODE: 6
=   CLEANING UP REMAINING PROCESSES
=   YOU CAN IGNORE THE BELOW CLEANUP MESSAGES
===================================================================================

Have you ever had an error like this?

Best,
Mattia

**Comment by bayesiancook** [comment]
Dear Mattia,

slow reply, sorry.. I assume this is a numerical error. I am currently working on a new version of cross-validation. If this problem appears again, then I could work this out.

best,

nicolas
