### ISSUE TITLE
How to use

### ISSUE THREAD

**Issue by Tianyou96** [bayesiancook/pbmpi#17]
mpirun -np 4 pb_mpi -d *.phy -t *.tree -cat -gtr -x 1 -1 chain1
mpirun -np 4 pb_mpi -d *.phy -t *.tree -cat -gtr -x 1 -1 chain2
suggest chains have 2
bpcomp -x 1 chain1 chain2   #maxdiff < 0.3  	
tracecomp -x 1 chain1 chain2  #effsize >50

**Comment by bayesiancook** [comment]
not sure to understand..
