### ISSUE TITLE
Do you have plans for a new release/tag? 

### ISSUE THREAD

**Issue by ggdagw** [bayesiancook/pbmpi#18]
Hi,

I've been exploring the use of pbmpi on ThunderX2 processors using the ARM compiler.  It goes well, but I see the negative time error with release 1.8b.  I was wondering if you were planning a new release with the fix for the negative time error, as I like to provide my cluster users with a released version wherever possible (mainly as a convenient aid to reproducibility).

Many thanks,
Gethin.

**Comment by bayesiancook** [comment]
Dear Gethin,

just did the release (v1.8c). Hope this helps.

nicolas

**Comment by ggdagw** [comment]
Thanks Nicolas—that’s great!
Very much appreciated.  I’ll install it on our ARM-based cluster now and let the users know.  They’ll get a good speed up from the improved vectorization produced by the ARMv20 compiler.
Best wishes,
Gethin.

On Oct 26, 2020, at 7:02 PM, bayesiancook <notifications@github.com<mailto:notifications@github.com>> wrote:



Dear Gethin,

just did the release (v1.8c). Hope this helps.

nicolas
