### ISSUE TITLE
compilation problem

### ISSUE THREAD

**Issue by faguil** [bayesiancook/pbmpi#19]
Hi,

I am trying to install pbmpi in a ubuntu machine and have troubles to compile it. Once I type "make" in the source folder, it takes so long in generating dependencies for each *.cpp files. Indeed, it is an endless process and the compilation never happens.

Any help would be appreciated.

Cheers,

Felipe

**Comment by bayesiancook** [comment]
did you try
make clean
make
?

**Comment by faguil** [comment]
I tried that and it worked but in a different Ubuntu machine that previous attempts.

Thanks,

Felipe
