### ISSUE TITLE
pb_mpi not working

### ISSUE THREAD

**Issue by Will338** [bayesiancook/pbmpi#2]
I'm getting the following errors when trying to run pb_mpi using this command:
`mpirun -np 6 pb_mpi ~/Path/to/data Chain1`
Please can anyone give me some guidance in how to get it working? 

>pb_mpi:
>
>error while loading shared libraries: libmpi_cxx.so.0: cannot open shared object file: No such file or directory
>pb_mpi: error while loading shared libraries: libmpi_cxx.so.0: cannot open shared object file: No such file or directory
>pb_mpi: error while loading shared libraries: libmpi_cxx.so.0: cannot open shared object file: No such file or directory
>pb_mpi: error while loading shared libraries: libmpi_cxx.so.0: cannot open shared object file: No such file or directory
>pb_mpi: error while loading shared libraries: libmpi_cxx.so.0: cannot open shared object file: No such file or directory
>pb_mpi: error while loading shared libraries: libmpi_cxx.so.0: cannot open shared object file: No such file or directory
>--------------------------------------------------------------------------
>mpirun noticed that the job aborted, but has no info as to the process
that caused that situation.
>--------------------------------------------------------------------------

**Comment by josephwb** [comment]
@Will338 I got the same error with the distributed binary. However, as the manual says:
>you may need to recompile the code

I did this and things work well. (Compiling only takes a, er, compiler, and the command `make` in the sources directory (binaries are put into the `data` directory).

HTH :bowtie:

**Comment by M1keAdams** [comment]
I have the same issue, but when I try to compile, I get the following when running make. Can someone point me in the right direction?

Tree.o: In function `Tree::ParseGroup(std::string, Link*)':
Tree.cpp:(.text+0x1be0): undefined reference to `std::__throw_out_of_range_fmt(char const*, ...)'
Tree.cpp:(.text+0x1c22): undefined reference to `std::__throw_out_of_range_fmt(char const*, ...)'
Tree.cpp:(.text+0x1c69): undefined reference to `std::__throw_out_of_range_fmt(char const*, ...)'
Tree.o: In function `Tree::ParseList(std::string, Node*)':
Tree.cpp:(.text+0x1d80): undefined reference to `std::__detail::_List_node_base::_M_hook(std::__detail::_List_node_base*)'
Tree.cpp:(.text+0x1e37): undefined reference to `std::__detail::_List_node_base::_M_hook(std::__detail::_List_node_base*)'
Tree.cpp:(.text+0x2269): undefined reference to `std::__throw_out_of_range_fmt(char const*, ...)'
Tree.cpp:(.text+0x22ba): undefined reference to `std::__throw_out_of_range_fmt(char const*, ...)'
CodonStateSpace.o: In function `CodonStateSpace::GetState(std::string)':
CodonStateSpace.cpp:(.text+0xd2c): undefined reference to `std::__throw_out_of_range_fmt(char const*, ...)'
CodonStateSpace.cpp:(.text+0xd69): undefined reference to `std::__throw_out_of_range_fmt(char const*, ...)'
PhyloProcess.o: In function `PhyloProcess::Read(std::string, int, int, int)':
PhyloProcess.cpp:(.text+0x9e02): undefined reference to `std::__detail::_List_node_base::_M_hook(std::__detail::_List_node_base*)'
PhyloProcess.cpp:(.text+0x9e84): undefined reference to `std::__detail::_List_node_base::_M_hook(std::__detail::_List_node_base*)'
PhyloProcess.o: In function `std::list<double, std::allocator<double> >::sort()':
PhyloProcess.cpp:(.text._ZNSt4listIdSaIdEE4sortEv[_ZNSt4listIdSaIdEE4sortEv]+0x76): undefined reference to `std::__detail::_List_node_base::_M_transfer(std::__detail::_List_node_base*, std::__detail::_List_node_base*)'
PhyloProcess.cpp:(.text._ZNSt4listIdSaIdEE4sortEv[_ZNSt4listIdSaIdEE4sortEv]+0xcf): undefined reference to `std::__detail::_List_node_base::_M_transfer(std::__detail::_List_node_base*, std::__detail::_List_node_base*)'
PhyloProcess.cpp:(.text._ZNSt4listIdSaIdEE4sortEv[_ZNSt4listIdSaIdEE4sortEv]+0xde): undefined reference to `std::__detail::_List_node_base::swap(std::__detail::_List_node_base&, std::__detail::_List_node_base&)'
PhyloProcess.cpp:(.text._ZNSt4listIdSaIdEE4sortEv[_ZNSt4listIdSaIdEE4sortEv]+0xf3): undefined reference to `std::__detail::_List_node_base::swap(std::__detail::_List_node_base&, std::__detail::_List_node_base&)'
PhyloProcess.cpp:(.text._ZNSt4listIdSaIdEE4sortEv[_ZNSt4listIdSaIdEE4sortEv]+0x11a): undefined reference to `std::__detail::_List_node_base::_M_transfer(std::__detail::_List_node_base*, std::__detail::_List_node_base*)'
PhyloProcess.cpp:(.text._ZNSt4listIdSaIdEE4sortEv[_ZNSt4listIdSaIdEE4sortEv]+0x13b): undefined reference to `std::__detail::_List_node_base::swap(std::__detail::_List_node_base&, std::__detail::_List_node_base&)'
PhyloProcess.cpp:(.text._ZNSt4listIdSaIdEE4sortEv[_ZNSt4listIdSaIdEE4sortEv]+0x18f): undefined reference to `std::__detail::_List_node_base::_M_transfer(std::__detail::_List_node_base*, std::__detail::_List_node_base*)'
PhyloProcess.cpp:(.text._ZNSt4listIdSaIdEE4sortEv[_ZNSt4listIdSaIdEE4sortEv]+0x1ae): undefined reference to `std::__detail::_List_node_base::swap(std::__detail::_List_node_base&, std::__detail::_List_node_base&)'
PhyloProcess.cpp:(.text._ZNSt4listIdSaIdEE4sortEv[_ZNSt4listIdSaIdEE4sortEv]+0x21a): undefined reference to `std::__detail::_List_node_base::_M_transfer(std::__detail::_List_node_base*, std::__detail::_List_node_base*)'
collect2: error: ld returned 1 exit status
make: *** [../data/pb_mpi] Error 1

**Comment by reneum** [comment]
We have the same issue here:
`pb_mpi: error while loading shared libraries: libmpi_cxx.so.0:`

But we are also unable to re-compile a functional binary:
```
...
In file included from AACodonMutSelProfileProcess.h:20:0,
                 from AACodonMutSelSBDPProfileProcess.h:21,
                 from AACodonMutSelSBDPSubstitutionProcess.h:20,
                 from AACodonMutSelSBDPPhyloProcess.h:20,
                 from Model.h:23,
                 from PB.cpp:17:
CodonSubMatrix.h:70:33: error: ‘constexpr’ needed for in-class initialization of static data member ‘const double AAMutSelProfileSubMatrix::TOOSMALL’ of non-integral type [-fpermissive]
  static const double TOOSMALL = 1e-30;
                                 ^~~~~
CodonSubMatrix.h:71:33: error: ‘constexpr’ needed for in-class initialization of static data member ‘const double AAMutSelProfileSubMatrix::TOOLARGE’ of non-integral type [-fpermissive]
  static const double TOOLARGE = 500;
                                 ^~~
CodonSubMatrix.h:72:42: error: ‘constexpr’ needed for in-class initialization of static data member ‘const double AAMutSelProfileSubMatrix::TOOLARGENEGATIVE’ of non-integral type [-fpermissive]
  static const double TOOLARGENEGATIVE = -500;
                                          ^~~
CodonSubMatrix.h:99:33: error: ‘constexpr’ needed for in-class initialization of static data member ‘const double AACodonMutSelProfileSubMatrix::TOOSMALL’ of non-integral type [-fpermissive]
  static const double TOOSMALL = 1e-30;
                                 ^~~~~
CodonSubMatrix.h:100:33: error: ‘constexpr’ needed for in-class initialization of static data member ‘const double AACodonMutSelProfileSubMatrix::TOOLARGE’ of non-integral type [-fpermissive]
  static const double TOOLARGE = 500;
                                 ^~~
CodonSubMatrix.h:101:42: error: ‘constexpr’ needed for in-class initialization of static data member ‘const double AACodonMutSelProfileSubMatrix::TOOLARGENEGATIVE’ of non-integral type [-fpermissive]
  static const double TOOLARGENEGATIVE = -50;
                                          ^~
CodonSubMatrix.h:122:33: error: ‘constexpr’ needed for in-class initialization of static data member ‘const double CodonMutSelProfileSubMatrix::TOOSMALL’ of non-integral type [-fpermissive]
  static const double TOOSMALL = 1e-30;
                                 ^~~~~
CodonSubMatrix.h:123:33: error: ‘constexpr’ needed for in-class initialization of static data member ‘const double CodonMutSelProfileSubMatrix::TOOLARGE’ of non-integral type [-fpermissive]
  static const double TOOLARGE = 500;
                                 ^~~
CodonSubMatrix.h:124:42: error: ‘constexpr’ needed for in-class initialization of static data member ‘const double CodonMutSelProfileSubMatrix::TOOLARGENEGATIVE’ of non-integral type [-fpermissive]
  static const double TOOLARGENEGATIVE = -50;
                                          ^~
make: *** [Makefile:55: PB.o] Error 1
make: *** Waiting for unfinished jobs....
```

Our versions:
```
reneum@mphn ~/builder/pbmpi/sources $ mpic++ -showme:version
mpic++: Open MPI 2.0.2 (Language: C++)

reneum@mphn ~/builder/pbmpi/sources $ mpic++ -showme
x86_64-pc-linux-gnu-g++ -pthread -Wl,-rpath -Wl,/usr/lib64 -Wl,--enable-new-dtags -L/usr/lib64 -lmpi_cxx -lmpi
```

`
gcc-6.4
`

Any advise?

**Comment by bayesiancook** [comment]
should recompile now, with the new version

Also, I have removed the binary files: you need to recompile on most machines anyway.
