### ISSUE TITLE
How to determine burin in bpcomp and tracecomp

### ISSUE THREAD

**Issue by dongzhang0725** [bayesiancook/pbmpi#21]
Hi all,

I wanna to know what is the proper burin threshold, now I set 25% of the total generation as burin, but I am not sure it is reasonable. Could anybody help me with this question?

Thank you for your help,

Dong

**Comment by bayesiancook** [comment]
Dear Dong,

there is no simple rule to set up the burnin; you need to have a look at the trace plot of the summary statistics that are in the trace file (starting from column number 4, which is also the most important one, the log likelihood): the burnin should be chosen such that the traces are stationary.

I hope this helps

best,

Nicolas

**Comment by dongzhang0725** [comment]
Dear Nicolas,

Thank you for your useful answer, now I know what to do with the burin strategy.

Best,

Dong
