### ISSUE TITLE
How to visually check chain convergence with large number of iterations? 

### ISSUE THREAD

**Issue by Ruiqi-CUB** [bayesiancook/pbmpi#34]
Hi there,

I was running ~20k iterations/chain and 3 chains for phylobayes-mpi. I would like to visualize the convergence of the 3 chains. I have done it with Tracer in the past, however, with 20k iterations, Tracer is having a hard time to open the chain files. Is there any other way to visually check chain convergence?

Thanks a lot!

**Comment by bayesiancook** [comment]
Dear Ruiqi-CUB

not sure why tracer would have problem with the trace files produced by pbmpi (which are not that big), but you can also use tracecomp to monitor the convergence.

best,

Nicolas

**Comment by bayesiancook** [comment]
closed
