### ISSUE TITLE
Compilation problem

### ISSUE THREAD

**Issue by RobertoDelAmparo** [bayesiancook/pbmpi#36]
Hi, 
I am trying to compile the latest version of the Phylobayes MPI program, and I am encountering the following error:

make: *** There is no rule to build the target 'PB.d', necessary for 'PB.o'.  Stop.

How could I fix it?
Thank you for your help

**Comment by bayesiancook** [comment]
Dear Roberto,

dead you try to clean first:

make clean

and then:

make

?

best,

Nicolas

**Comment by bayesiancook** [comment]
closed

**Comment by bayesiancook** [comment]
closed
