### ISSUE TITLE
How to compute the site-specific state equilibrium frequencies for each MCMC generation?

### ISSUE THREAD

**Issue by ZQ1126** [bayesiancook/pbmpi#37]
Hi,
According to your manual, I know that readpb_mpi with the -ss command can obtain the mean posterior site-specific state equilibrium frequencies (i.e., profile). However, now I want to obtain the profile for each generation of MCMC. I did not find relevant instructions in the manual. Could you please provide some advice? I have tried the following: 
mpirun -np 56 readpb_mpi -x 13009 1 13010 -ss chainname
but I am not sure if this will obtain the profile for generation 13010.
I look forward to receiving your reply, thank you.

**Comment by bayesiancook** [comment]
Hi,
yes, that's exactly that.
best,
bayesiancook

**Comment by bayesiancook** [comment]
closed

**Comment by bayesiancook** [comment]
closed
