### ISSUE TITLE
readpb_mpi error

### ISSUE THREAD

**Issue by bailliecharles** [bayesiancook/pbmpi#5]
Getting the following half way though running:
mpirun -np 100 /SOFTWARE/pbmpi/data/readpb_mpi -x 2000 -div CHAIN1

.............................................in tree: null string

Any ideas/
Thanks
C

**Comment by bayesiancook** [comment]
apparently, this sometimes happens when the .chain is corrupted.

**Comment by gerthmicha** [comment]
Hi, could you provide some more information on this please? I have also encountered the error 
`in tree: null string` multiple times but don't understand how the .chain file can become corrupted or how to avoid this. Is there a way to 'repair' the chain file? Any ideas would be really helpful, thanks!

**Comment by nicrodrigue** [comment]
I suspect that some taxa names are entirely numerical in your data set.  If this is the case, the parsing of trees produced by the software will run into the problems, with a confusion between branch lengths and taxa names.


In the future, try adding a letter to your taxa names to avoid the confusion.


Regards,


Nic

________________________________

**Comment by gerthmicha** [comment]
Hi Nic, thanks for the feedback. Non of the taxa in my dataset are entirely numerical. I did stop the runs though, performed some posterior predictive tests (which worked out fine), then continued the runs and stopped them again after some more iterations. After this, the error occurs. 
Cheers, Michael
